// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CriarContaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void criarConta() {
    // Test name: Criar Conta
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://seubarriga.wcaquino.me/");
    // 2 | setWindowSize | 1954x1053 | 
    driver.manage().window().setSize(new Dimension(1954, 1053));
    // 3 | click | css=.caret | 
    driver.findElement(By.cssSelector(".caret")).click();
    // 4 | click | linkText=Adicionar | 
    driver.findElement(By.linkText("Adicionar")).click();
    // 5 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 6 | type | id=nome | Conta 5
    driver.findElement(By.id("nome")).sendKeys("Conta 5");
    // 7 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 8 | waitForText | css=.alert | Conta adicionada com sucesso!
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.textToBe(By.cssSelector(".alert"), "Conta adicionada com sucesso!"));
    }
  }
}
